name: CI

on:
    workflow_dispatch:

jobs:
    windows:
        runs-on: windows-latest

        steps:
          - uses: actions/checkout@v4

          - name: Setup Haxe
            uses: krdlab/setup-haxe@master
            with:
              haxe-version: 4.3.6

          - name: Setup Haxelib Directory
            run: |
              mkdir C:/haxelib
              haxelib setup C:/haxelib
            shell: cmd

          - name: Cache Haxelib dependencies
            uses: actions/cache@v4
            with:
              path: C:/haxelib
              key: ${{ runner.os }}-haxelib-${{ hashFiles('**/setup/Main.hx') }}
              restore-keys: |
                ${{ runner.os }}-haxelib-

          - name: Install Haxelib Dependencies
            run: |
              echo BEFORE INSTALLING!!!
              haxelib list
              haxelib install hxcpp --quiet
              haxelib install lime 8.2.0 --quiet
              haxelib install openfl 9.3.4 --quiet
              haxelib install flixel --quiet
              haxelib git extended-flixel https://github.com/MrMadera/extended-flixel --quiet
              echo AFTER INSTALLING!!!
              haxelib list
            shell: cmd

            # haxe -cp ./setup -D analyzer-optimize -main Main --interp

          - name: Create Version Tag
            run: echo "${{ github.run_id }}" > VERSION

          - name: Compile
            run: cmd /c "cd tests & haxelib run lime build windows --app-version="4.0.0-${{ github.run_id }}"
            shell: cmd

          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
              path: tests/export/windows/bin
              name: windowsBuild
              retention-days: 1

    cancel_previous_workflows:
        runs-on: ubuntu-latest
        permissions: 
          actions: write
        
        steps:
          - name: Cancel previous workflows
            uses: styfle/cancel-workflow-action@0.9.1
            with:
              access_token: ${{ github.token }}