name: CI

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    windows:
        runs-on: windows-latest

        steps:
          - uses: actions/checkout@v4

          - name: Setup Haxe
            uses: krdlab/setup-haxe@master
            with:
              haxe-version: 4.3.6

          - name: Cache Haxelib dependencies
            uses: actions/cache@v4
            with:
              path: C:/haxelib
              key: ${{ runner.os }}-haxelib-${{ github.run_id }} # Unique for each workflow run
              restore-keys: |
                ${{ runner.os }}-haxelib-

          - name: Install Haxelib
            run: |
              haxelib setup C:/haxelib
              haxelib list
              haxelib install hxcpp --quiet
              haxe -cp ./setup -D analyzer-optimize -main Main --interp
            shell: cmd

          - name: Update Cache
            if: always() # Update the cache regardless of workflow success/failure
            uses: actions/cache@v4
            with:
              path: C:/haxelib
              key: ${{ runner.os }}-haxelib-${{ github.run_id }}

          - name: Create Version Tag
            run: echo "${{ github.run_id }}" > VERSION

          - name: Compile
            run: cmd /c "cd tests & haxelib run lime build windows --app-version="4.0.0-${{ github.run_id }}"
            shell: cmd

          - name: Upload artifact
            uses: actions/upload-artifact@v3
            with:
              path: tests/export/windows/bin
              name: windowsBuild
              retention-days: 1

    cancel_previous_workflows:
        runs-on: ubuntu-latest
        permissions: 
          actions: write
        
        steps:
          - name: Cancel previous workflows
            uses: styfle/cancel-workflow-action@0.9.1
            with:
              access_token: ${{ github.token }}