name: CI

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    buildWindows:
        runs-on: windows-latest

        steps:
          - uses: actions/checkout@v4

          - name: Setup Haxe
            uses: krdlab/setup-haxe@master
            with:
              haxe-version: 4.3.6

          - name: Install Haxelib
            run: |
              haxelib setup C:/haxelib
              haxelib install hxcpp --quiet
              haxelib --global install hmm
              haxelib --global run hmm setup 
              hmm install
            shell: cmd
          - name: Skip SScript setup mode
            run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> ~/settings.cocoa

          - name: Create Version Tag
            run: echo "${{ github.run_id }}" > VERSION

          - name: Compile
            run: cmd /c "cd tests & haxelib run lime build windows --app-version="4.0.0-${{ github.run_id }}"
            shell: cmd
